format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$line_break\
$jobs\
$battery\
$time\
$status\
$character"""

[character]
success_symbol = "▸"
error_symbol = "[!](bold red)"

[directory]
truncate_to_repo = true

[line_break]
disabled = false

[git_branch]
symbol=""
